#!/bin/bash
set -e

# INstall Brew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
# Add Homebrew to PATH for the rest of this script
if [[ "$(uname -m)" == "arm64" ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"  # Apple Silicon
else
    eval "$(/usr/local/bin/brew shellenv)"      # Intel Mac
fi

brew install curl
brew install glow
brew install tree

brew install --cask firefox
brew install --cask claude-code
brew install --cask tailscale-app
brew install --cask keyboardcleantool
brew install --cask spotify
brew install --cask claude-code
brew install gemini-cli

# Create/edit Ghostty config
brew install --cask ghostty
mkdir -p ~/.config/ghostty
echo 'theme = Dracula' >> ~/.config/ghostty/config
echo 'term = xterm-256color' >> ~/.config/ghostty/config

brew install --cask visual-studio-code
code --install-extension dracula-theme.theme-dracula
mkdir -p "$HOME/Library/Application Support/Code/User"
cat >> "$HOME/Library/Application Support/Code/User/settings.json" << 'EOF'
{
  "workbench.colorTheme": "Dracula"
}
EOF

# Install UV
curl -LsSf https://astral.sh/uv/install.sh | less

# Install ohmzsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
