#!/bin/bash
set -e

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

brew install curl
brew install glow
brew install tree

brew install --cask visual-studio
brew install --cask ghostty
brew install --cask firefox
brew install --cask claude-code
brew install --cask tailscale-app
brew install --cask spotify

# Install UV
curl -LsSf https://astral.sh/uv/install.sh | less

# Install ohmzsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
